Entity/Media/AbstractMediaEntity.php
<?php

namespace Cmfcmf\Module\MediaModule\Entity\Media;

use Cmfcmf\Module\MediaModule\Entity\Collection\CollectionEntity;
use Cmfcmf\Module\MediaModule\Entity\HookedObject\HookedObjectEntity;
use Cmfcmf\Module\MediaModule\Entity\HookedObject\HookedObjectMediaEntity;
use Cmfcmf\Module\MediaModule\Entity\License\LicenseEntity;
use Cmfcmf\Module\MediaModule\MediaType\MediaTypeCollection;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;
use DoctrineExtensions\StandardFields\Mapping\Annotation as ZK;

use Gedmo\Sluggable\Sluggable;
use Gedmo\Sortable\Sortable;

/**
 * @ORM\Entity(repositoryClass="Cmfcmf\Module\MediaModule\Entity\Media\Repository\MediaRepository")
 * @ORM\Table(name="cmfcmfmedia_media")
 * @ORM\HasLifecycleCallbacks()
 *
 * @ORM\InheritanceType(value="SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="discr")
 * @ORM\DiscriminatorMap({
 *  "deezer"         = "DeezerEntity",
 *  "soundcloud"     = "SoundCloudEntity",
 *  "twitter"        = "TwitterEntity",
 *  "flickr"         = "FlickrEntity",
 *  "youtube"        = "YouTubeEntity",
 *  "url"            = "WebEntity",
 *  "image"          = "ImageEntity",
 *  "pdf"            = "PdfEntity",
 *  "plaintext"      = "PlaintextEntity",
 *  "markdown"       = "MarkdownEntity",
 *  "archive"        = "ArchiveEntity",
 *  "file"           = "AbstractFileEntity",
 *  "video"          = "VideoEntity",
 *  "audio"          = "AudioEntity",
 * })
 */
abstract class AbstractMediaEntity implements Sluggable, Sortable
{
    /**
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     *
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(type="integer")
     * @ORM\Version
     *
     * @var integer
     */
    private $version;

    /**
     * @Gedmo\SortablePosition
     * @ORM\Column(name="position", type="integer")
     */
    protected $position;

    /**
     * @ORM\Column(name="title", type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Length(max="255")
     *
     * @var string
     */
    protected $title;

    /**
     * @Gedmo\Slug(fields={"title"}, unique_base="collection", unique=true)
     * @ORM\Column(length=128)
     */
    protected $slug;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     *
     * @var string
     */
    protected $description;

    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     * @Assert\Length(max="255")
     *
     * @var string
     */
    protected $author;

    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     * @Assert\Length(max="255")
     * @Assert\Url()
     *
     * @var string
     */
    protected $authorUrl;

    /**
     * @ORM\Column(type="string", nullable=true, length=255)
     * @Assert\Length(max="255")
     * @Assert\Url()
     *
     * @var string
     */
    protected $authorAvatarUrl;

    /**
     * @ORM\Column(type="array")
     *
     * @var array
     */
    protected $extraData;

    /**
     * @ORM\ManyToOne(targetEntity="Cmfcmf\Module\MediaModule\Entity\License\LicenseEntity", fetch="EAGER")
     *
     * @var LicenseEntity|null
     **/
    protected $license;

    /**
     * @Gedmo\SortableGroup
     * @ORM\ManyToOne(targetEntity="Cmfcmf\Module\MediaModule\Entity\Collection\CollectionEntity", inversedBy="media")
     *
     * @var CollectionEntity
     */
    protected $collection;

    /**
     * @ORM\OneToMany(targetEntity="Cmfcmf\Module\MediaModule\Entity\HookedObject\HookedObjectMediaEntity", mappedBy="media", fetch="EXTRA_LAZY", cascade={"persist"})
     *
     * @var HookedObjectMediaEntity[]|ArrayCollection
     */
    protected $hookedObjectMedia;

    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="create")
     * @var integer $createdUserId.
     */
    protected $createdUserId;

    /**
     * @ORM\Column(type="integer")
     * @ZK\StandardFields(type="userid", on="update")
     * @var integer $updatedUserId.
     */
    protected $updatedUserId;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="create")
     * @var \DateTime $createdDate.
     */
    protected $createdDate;

    /**
     * @ORM\Column(type="datetime")
     * @Gedmo\Timestampable(on="update")
     * @var \DateTime $updatedDate.
     */
    protected $updatedDate;

    public function __construct()
    {
        // Position at the end of the album.
        $this->position = -1;
        $this->extraData = [];
        $this->hookedObjectMedia = new ArrayCollection();
    }

    public function getImagineId()
    {
        return "media-{$this->id}";
    }

    public function getAttribution()
    {
        if ($this->author === null && $this->authorUrl === null) {
            return null;
        }
        $dom = \ZLanguage::getModuleDomain('CmfcmfMediaModule');

        if ($this->author === null) {
            $author = '<a href="' . htmlentities($this->authorUrl). '">' . htmlentities($this->author) . '</a>';

            return __f('Content of %s', [$author], $dom);
        }

        if ($this->authorUrl === null) {
            $author = htmlentities($this->author);
        } else {
            $author = '<a href="' . htmlentities($this->authorUrl). '">' . htmlentities($this->author) . '</a>';
        }
        return __f('Content of %s', [$author], $dom);
    }

    /**
     * @return CollectionEntity
     */
    public function getCollection()
    {
        return $this->collection;
    }

    /**
     * @param CollectionEntity $collection
     *
     * @return $this
     */
    public function setCollection($collection)
    {
        $this->collection = $collection;
        return $this;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * @param mixed $slug
     * @return $this
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;
        return $this;
    }
    
    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return $this
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set license
     *
     * @param LicenseEntity $license
     * @return $this
     */
    public function setLicense($license)
    {
        $this->license = $license;

        return $this;
    }

    /**
     * Get license
     *
     * @return LicenseEntity|null
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * @return int
     */
    public function getCreatedUserId()
    {
        return $this->createdUserId;
    }

    /**
     * @param int $createdUserId
     * @return $this
     */
    public function setCreatedUserId($createdUserId)
    {
        $this->createdUserId = $createdUserId;
        return $this;
    }

    /**
     * @return int
     */
    public function getUpdatedUserId()
    {
        return $this->updatedUserId;
    }

    /**
     * @param int $updatedUserId
     * @return $this
     */
    public function setUpdatedUserId($updatedUserId)
    {
        $this->updatedUserId = $updatedUserId;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getCreatedDate()
    {
        return $this->createdDate;
    }

    /**
     * @param \DateTime $createdDate
     * @return $this
     */
    public function setCreatedDate($createdDate)
    {
        $this->createdDate = $createdDate;
        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getUpdatedDate()
    {
        return $this->updatedDate;
    }

    /**
     * @param \DateTime $updatedDate
     * @return $this
     */
    public function setUpdatedDate($updatedDate)
    {
        $this->updatedDate = $updatedDate;
        return $this;
    }

    /**
     * @return mixed
     */
    public function getPosition()
    {
        return $this->position;
    }

    /**
     * @param mixed $position
     * @return $this
     */
    public function setPosition($position)
    {
        $this->position = $position;
        return $this;
    }

    /**
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * @param string $author
     * @return $this
     */
    public function setAuthor($author)
    {
        $this->author = $author;
        return $this;
    }

    /**
     * @return string
     */
    public function getAuthorAvatarUrl()
    {
        return $this->authorAvatarUrl;
    }

    /**
     * @param string $authorAvatarUrl
     * @return $this
     */
    public function setAuthorAvatarUrl($authorAvatarUrl)
    {
        $this->authorAvatarUrl = $authorAvatarUrl;
        return $this;
    }

    /**
     * @param array $extraData
     * @return $this
     */
    public function setExtraData($extraData)
    {
        $this->extraData = $extraData;
        return $this;
    }

    /**
     * @param array $extraData
     * @return $this
     */
    public function addExtraData($extraData)
    {
        $this->extraData = array_merge($this->extraData, $extraData);
        return $this;
    }

    /**

Entity/Media/MarkdownEntity.php
<?php

namespace Cmfcmf\Module\MediaModule\Entity\Media;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class MarkdownEntity extends AbstractFileEntity
{

}

Entity/Media/PdfEntity.php
<?php

namespace Cmfcmf\Module\MediaModule\Entity\Media;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class PdfEntity extends AbstractFileEntity
{
    public function onNewFile(array $info)
    {
        parent::onNewFile($info);

        // @todo read meta tags.
    }
}

Entity/Media/PlaintextEntity.php
<?php

namespace Cmfcmf\Module\MediaModule\Entity\Media;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity()
 */
class PlaintextEntity extends AbstractFileEntity
{
    public function __construct()
    {
        parent::__construct();

        $this->setUseSyntaxHighlighting(true);
    }

    public function getUseSyntaxHighlighting()
    {
        return isset($this->extraData['useSyntaxHighlighting']) ? $this->extraData['useSyntaxHighlighting'] : false;
    }

    public function setUseSyntaxHighlighting($useSyntaxHighlighting)
    {
        $this->extraData['useSyntaxHighlighting'] = $useSyntaxHighlighting;
    }
}

Form/Media/AbstractFileType.php
<?php

namespace Cmfcmf\Module\MediaModule\Form\Media;

use Symfony\Component\Form\FormBuilderInterface;

class AbstractFileType extends AbstractMediaEntityType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $builder
            ->add('file', 'file', [
                'label' => $this->__('Change file'),
                'mapped' => false,
                'required' => false
            ])
            ->add('downloadAllowed', 'checkbox', [
                'required' => false,
                'label' => $this->__('Allow download')
            ])
        ;
    }
}

Form/Media/AbstractMediaEntityType.php
<?php

namespace Cmfcmf\Module\MediaModule\Form\Media;

use Cmfcmf\Module\MediaModule\Entity\Collection\CollectionEntity;
use Cmfcmf\Module\MediaModule\Entity\License\LicenseEntity;
use Cmfcmf\Module\MediaModule\Form\AbstractType;
use Cmfcmf\Module\MediaModule\Form\DataTransformer\ArrayToJsonTransformer;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\FormBuilderInterface;
use Zikula\Common\I18n\TranslatableInterface;

abstract class AbstractMediaEntityType extends AbstractType implements TranslatableInterface
{
    /**
     * @var bool
     */
    protected $isCreation;

    /**
     * @var CollectionEntity|null
     */
    private $parent;

    /**
     * @var bool
     */
    private $allowTemporaryUploadCollection;

    public function __construct($isCreation = false, CollectionEntity $parent = null, $allowTemporaryUploadCollection = false)
    {
        parent::__construct();

        $this->isCreation = $isCreation;
        $this->parent = $parent;
        $this->allowTemporaryUploadCollection = $allowTemporaryUploadCollection;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        parent::buildForm($builder, $options);

        $escapingStrategy = \ModUtil::getVar('CmfcmfMediaModule', 'descriptionEscapingStrategyForMedia');
        switch ($escapingStrategy) {
            case 'raw':
                $descriptionHelp = $this->__('You may use HTML.');
                break;
            case 'text':
                $descriptionHelp = $this->__('Only plaintext allowed.');
                break;
            case 'markdown':
                $descriptionHelp = $this->__('You may use MarkDown.');
                break;
            default:
                throw new \LogicException();
        }

        $hiddenAttr = [
            'class' => 'hidden',
        ];

        $allowTemporaryUploadCollection = $this->allowTemporaryUploadCollection;
        $collectionOptions = [
            'required' => true,
            'label' => $this->__('Collection'),
            'class' => 'CmfcmfMediaModule:Collection\CollectionEntity',
            'query_builder' => function(EntityRepository $er) use ($allowTemporaryUploadCollection) {
                $qb = $er->createQueryBuilder('c');
                $qb
                    ->orderBy('c.root', 'ASC')
                    ->addOrderBy('c.lft', 'ASC')
                ;
                if (!$allowTemporaryUploadCollection) {
                    $qb->where($qb->expr()->not($qb->expr()->eq('c.id', ':uploadCollectionId')))
                        ->setParameter('uploadCollectionId', CollectionEntity::TEMPORARY_UPLOAD_COLLECTION_ID);
                    ;
                }

                return $qb;
            },
            'placeholder' => $this->__('Select collection'),
            'property' => 'indentedTitle',
        ];
        if ($this->parent !== null) {
            $collectionOptions['data'] = $this->parent;
        }

        $builder
            ->add('collection', 'entity', $collectionOptions)
            ->add('title', isset($options['hiddenFields']) && in_array('title', $options['hiddenFields']) ? 'hidden' : 'text', [
                'label' => $this->__('Title')
            ])
            ->add('description', isset($options['hiddenFields']) && in_array('description', $options['hiddenFields']) ? 'hidden' : 'textarea', [
                'required' => false,
                'label' => $this->__('Description'),
                'attr' => [
                    'help' => $descriptionHelp
                ]
            ])
            ->add('license', 'entity', [
                'required' => false,
                'label' => $this->__('License'),
                'class' => 'CmfcmfMediaModule:License\LicenseEntity',
                'preferred_choices' => function (LicenseEntity $license) {
                    return !$license->isOutdated();
                },
                'query_builder' => function (EntityRepository $er) {
                    return $er->createQueryBuilder('l')
                        ->orderBy('l.title', 'ASC')
                        ->where('l.enabledForUpload = 1');
                        // @todo Move to the actual uploadable file types.
                },
                'placeholder' => $this->__('Unknown'),
                'property' => 'title',
                'attr' => isset($options['hiddenFields']) && in_array('license', $options['hiddenFields']) ? $hiddenAttr : [],
                'label_attr' => isset($options['hiddenFields']) && in_array('license', $options['hiddenFields']) ? $hiddenAttr : []
            ])
            ->add('author', isset($options['hiddenFields']) && in_array('author', $options['hiddenFields']) ? 'hidden' : 'text', [
                'label' => $this->__('Author'),
                'required' => false,
                'empty_data' => null
            ])
            ->add('authorUrl', isset($options['hiddenFields']) && in_array('authorUrl', $options['hiddenFields']) ? 'hidden' : 'url', [
                'label' => $this->__('Author URL'),
                'required' => false,
                'empty_data' => null
            ])
            ->add('authorAvatarUrl', isset($options['hiddenFields']) && in_array('authorAvatarUrl', $options['hiddenFields']) ? 'hidden' : 'url', [
                'label' => $this->__('Author Avatar URL'),
                'required' => false,
                'empty_data' => null
            ])
            ->add('mediaType', 'hidden', [
                'mapped' => false
            ])
            ->add('extraData', 'hidden')
        ;

        $builder->get('extraData')->addModelTransformer(new ArrayToJsonTransformer());
    }
}

Form/Media/ArchiveType.php
<?php

namespace Cmfcmf\Module\MediaModule\Form\Media;

class ArchiveType extends AbstractFileType
{

}

Form/Media/AudioType.php
<?php

namespace Cmfcmf\Module\MediaModule\Form\Media;

class AudioType extends AbstractFileType
{

}

Resources/views/Media/AdminList.html.twig
{% extends 'CmfcmfMediaModule::AdminBase.html.twig' %}
{% block title __('Media list') %}
{% block content %}
    <div class="table-responsive">
        <table class="table table-condensed table-striped">
            <thead>
            <tr>
                {#<th>{{ __('Position') }}</th>#}
                <th>{{ __('Id') }}</th>
                <th>{{ __('Thumbnail') }}</th>
                <th>{{ __('Title') }}</th>
                <th>{{ __('Collection') }}</th>
                <th>{{ __('License') }}</th>
                <th>{{ __('Actions') }}</th>
            </tr>
            </thead>
            <tbody>
            {% for entity in paginator %}
                <tr>
                    {#<td>{{ entity.position }}</td>#}
                    <td>
                        <a href="{{ path('cmfcmfmediamodule_media_display', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}">
                            {{ entity.id }}
                        </a>
                    </td>
                    <td>
                        {% set mediaType = mediaTypeCollection.mediaTypeFromEntity(entity) %}
                        {% set thumbnail =  mediaType.thumbnail(entity, 200, 100, 'url') %}
                        {% if thumbnail %}
                            <img src="{{ thumbnail|e('html_attr') }}" alt="{{ entity.title|e('html_attr') }}" style="max-width: 200px; max-height: 100px" />
                        {% else %}
                            <i class="fa fa-fw fa-5x {{ mediaType.icon }}"></i>
                        {% endif %}
                    </td>
                    <td>{{ entity.title }}</td>
                    <td>{{ entity.collection.title }}</td>
                    <td>{% if entity.license %}{{ entity.license.title }}{% else %}--{% endif %}</td>
                    <td class="text-right">
                        <a href="{{ path('cmfcmfmediamodule_media_display', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" title="{{ __('Show')|e('html_attr') }}">
                            <i class="fa fa-fw fa-eye"></i>
                        </a>
                        <a href="{{ path('cmfcmfmediamodule_media_edit', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}">
                            <i class="fa fa-fw fa-edit"></i>
                        </a>
                        <a href="{{ path('cmfcmfmediamodule_media_delete', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}">
                            <i class="fa fa-fw fa-trash-o text-danger"></i>
                        </a>
                    </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="8" class="text-center warning">
                        {{ __('No media available yet!') }}
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <nav>
        <ul class="pager">
            <li class="previous{% if page == 1 %} disabled{% endif %}">
                <a href="{{ path('cmfcmfmediamodule_media_adminlist', {page: (page - 1)}) }}">
                    <span aria-hidden="true">&larr;</span> {{ __('Previous') }}
                </a>
            </li>
            <li class="next{% if page == maxPage %} disabled{% endif %}">
                <a href="{{ path('cmfcmfmediamodule_media_adminlist', {page: (page + 1)}) }}">
                    {{ __('Next') }} <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
    {% if cmfcmfmediamodule_hasPermission('media', 'new') %}
        <a href="{{ path('cmfcmfmediamodule_media_new') }}" class="btn btn-default">
            <i class="fa fa-fw fa-plus"></i> {{ __('Create new media') }}
        </a>
    {% endif %}
{% endblock %}

Resources/views/Media/Create.html.twig
{% extends 'CmfcmfMediaModule::Base.html.twig' %}
{% block title __('Create new media') %}
{% block content %}
    {% include 'CmfcmfMediaModule::util.html.twig' %}
    {% form_theme form 'CmfcmfMediaModule:Form:bootstrap_3.html.twig' %}

    {{ form_start(form) }}
    {{ form_widget(form) }}

    {{ hook|raw }}

    <div class="col-sm-offset-2 col-sm-10">
        <button class="btn btn-success" type="submit">
            {{ __('Save') }}
        </button>
    </div>
    {{ form_end(form) }}
{% endblock %}

Resources/views/Media/Delete.html.twig
{% extends 'CmfcmfMediaModule::Base.html.twig' %}
{% block title %}
    {{ entity.title }}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xs-12">
            <div class="alert alert-danger">
                {{ __('Do you really want to delete this media object?') }}
            </div>
            <div class="col-sm-offset-2 col-sm-10 col-xs-12">
                <form action="{{ path('cmfcmfmediamodule_media_delete', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" method="post">
                    <button type="submit" class="btn btn-danger">
                        {{ __('Delete') }}
                    </button>
                    <a href="{{ path('cmfcmfmediamodule_media_display', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" class="btn btn-default">
                        {{ __('Cancel') }}
                    </a>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

Resources/views/Media/Display.html.twig
{% extends 'CmfcmfMediaModule::Base.html.twig' %}
{% block title %}
    {{ entity.title }}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-lg-9 col-md-9 col-sm-12">
            {{ mediaType.renderFullpage(entity)|raw }}

            {% if entity.description is not empty %}
                {{ entity|cmfcmfmediamodule_getdescription }}
            {% endif %}
        </div>
        <div class="col-lg-3 col-md-3 col-sm-12">
            <div class="well well-sm">
                {% if entity.license %}
                    <p>
                        <strong>{{ __('License') }}</strong>: {{ entity.license.title }} <br />
                        <a href="{{ entity.license.url }}">{{ entity.license.url }}</a>
                    </p>
                {% endif %}
                {% if entity.authorAvatarUrl is not empty %}
                    <img src="{{ entity.authorAvatarUrl }}" class="img img-rounded pull-right" alt="{{ __('Author avatar') }}" width="60" height="60" />
                {% endif %}
                {% if entity.attribution is not empty %}
                    <p>
                        {{ entity.attribution|raw }}
                    </p>
                {% endif %}
                <div class="clearfix"></div>
                <p>
                    <strong>{{ __('Added by') }}</strong>: {{ entity.createdUserId|cmfcmfmediamodule_unamefromuid }}
                    {{ __('at ') }} {{ entity.createdDate.format('d.m.Y H:i') }} <!-- @todo Internationalize -->
                    <img src="{{ entity.createdUserId|cmfcmfmediamodule_avatarfromuid }}" class="img img-rounded pull-right" alt="" width="60" height="60" />
                    <div class="clearfix"></div>
                </p>
            </div>
            {% set extendedMetaInformation = mediaType.extendedMetaInformation(entity) %}
            {% if extendedMetaInformation is not empty %}
                <div class="well well-sm">
                    {% for information in extendedMetaInformation %}
                        <p>
                            <strong>{{ information.title }}:</strong>
                            {{ information.value }}
                        </p>
                    {% endfor %}
                </div>
            {% endif %}
            <div class="list-group">
                {% if entity.downloadAllowed is defined and entity.downloadAllowed and cmfcmfmediamodule_hasPermission(entity, 'download') %}
                    <a href="{{ path('cmfcmfmediamodule_media_download', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" class="list-group-item">
                        <i class="fa fa-fw fa-download"></i>
                        {{ __('Download') }}
                    </a>
                {% endif %}
                {% if cmfcmfmediamodule_hasPermission(entity.collection, 'display') %}
                    <a href="{{ path('cmfcmfmediamodule_collection_display', {slug: entity.collection.slug}) }}" class="list-group-item">
                        <i class="fa fa-fw fa-picture-o"></i>
                        {{ __('Back to the collection') }}
                    </a>
                {% endif %}
                {% if cmfcmfmediamodule_hasPermission('media', 'admin') %}
                    <a href="{{ path('cmfcmfmediamodule_media_adminlist') }}" class="list-group-item">
                        <i class="fa fa-fw fa-arrow-left"></i>
                        {{ __('Back to the list') }}
                    </a>
                {% endif %}
                {% if cmfcmfmediamodule_hasPermission(entity, 'edit') %}
                    <a href="{{ path('cmfcmfmediamodule_media_edit', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" class="list-group-item list-group-item-warning">
                        <i class="fa fa-fw fa-edit"></i>
                        {{ __('Edit') }}
                    </a>
                {% endif %}
                {% if cmfcmfmediamodule_hasPermission(entity, 'delete') %}
                    <a href="{{ path('cmfcmfmediamodule_media_delete', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" class="list-group-item list-group-item-danger">
                        <i class="fa fa-fw fa-trash-o"></i>
                        {{ __('Delete') }}
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    {{ hook|raw }}
{% endblock %}

Resources/views/Media/Edit.html.twig
{% extends 'CmfcmfMediaModule::Base.html.twig' %}
{% block title __('Edit') ~ ' "' ~ entity.title ~ '"' %}
{% block content %}
    {% include 'CmfcmfMediaModule::util.html.twig' %}
    {% form_theme form 'CmfcmfMediaModule:Form:bootstrap_3.html.twig' %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <div class="col-sm-offset-2 col-sm-offset-10">
            {{ hook|raw }}
        </div>
        <div class="col-sm-offset-2 col-sm-offset-10">
            <button type="submit" class="btn btn-success">
                <i class="fa fa-fw fa-save"></i> {{ __('Save') }}
            </button>
            <a href="{{ path('cmfcmfmediamodule_media_display', {slug: entity.slug, collectionSlug: entity.collection.slug}) }}" class="btn btn-default">
                <i class="fa fa-fw fa-ban"></i> {{ __('Cancel') }}
            </a>
        </div>
    {{ form_end(form) }}
{% endblock %}

Resources/views/Media/HookView.html.twig
{% if hookedObjectMedia is not empty %}
    <h3>{{ __('Media') }}</h3>
    {% for hookedObjectMedium in hookedObjectMedia %}
        <h4>{{ hookedObjectMedium.media.title }}</h4>
        {{ mediaTypeCollection.mediaTypeFromEntity(hookedObjectMedium.media).embedCode(hookedObjectMedium.media, 'medium')|raw }}
    {% endfor %}
{% endif %}